### ISSUE TITLE
Project#copy_issues: issue #21936 could not be copied: ["ProjectEnumeration is not included in the list"]

### ISSUE THREAD

**Issue by linchao0815** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#17]
When I copy project will be fail which issue has the custom field that create with this plugins.
Please help me!

**Comment by Utopism** [comment]
Hi just tested, issues with Project Enumerations are not copied, because it does not found the project enumerations that are not copied (see the checkboxes there is none for project enumerations).

This feature was not developed, Could be not so complicated to do, but I have no time for it.

As a workaround you can follow this :
- Copy the project without copying the issues
- Make the new project a children of the source
- Configure you Project Enumerations values in parent project to be shared with sub-projects
- Copy the issues from parent to children
You project enumeration values should be present in the copied issue.

**Comment by linchao0815** [comment]
This problem is triggered by the use of baselines of easy gannt pro.
I reproduce same case in project copy.
Any suggest?

**Comment by Utopism** [comment]
I don't know how baselines work, but you have the answer in my previous comment :
Project Enumerations (which in a specific plugin table) are not copied by native Redmine project copy, so when copying an issue with project enumeration value, the project enumeration is not found in the new project resulting to the error you copied in the issue.

**Comment by linchao0815** [comment]
The ERROR produce below code "if new_issue.new_record?"


in redmine
app/models/project.rb
...
  # Copies issues from +project+
  def copy_issues(project)
    # Stores the source issue id as a key and the copied issues as the
    # value.  Used to map the two together for issue relations.
    issues_map = {}
....
      self.issues << new_issue
      if new_issue.new_record?
        logger.info "Project#copy_issues: issue ##{issue.id} could not be copied: #{new_issue.errors.full_messages}" if logger && logger.info?
      else
        issues_map[issue.id] = new_issue unless new_issue.new_record?
      end

**Comment by linchao0815** [comment]
How can I avoid the ERROR "new_issue.new_record?". 
In my case baseline just need the schedule date info.
How can I copy issue without custom field "project Enumerations " in "redmine ruby code"?

**Comment by linchao0815** [comment]
Thanks, I need modify code in easy gannt plugins to avoid the ERROR!
